from holosoma_retargeting.retargeter.interaction_mesh_retargeter import InteractionMeshRetargeter
from holosoma_retargeting.src.interaction_mesh_retargeter import InteractionMeshRetargeter as LegacyRetargeter


def test_retargeter_new_and_legacy_imports_resolve_same_class() -> None:
    assert InteractionMeshRetargeter is LegacyRetargeter
